// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzSA5d_g2a-R0C-KD8n-itejU4m9c',
    appId: '1:203312333339:android:42744e456b2ebe',
    messagingSenderId: '203312333339',
    projectId: 'konkukbulls-2d7ab',
    databaseURL: 'https://konkukbulls-2d7ab-default-rtdb.firebaseio.com',
    storageBucket: 'konkukbulls-2d7ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzikuZ_1UEcwgWxcQP61_Du38wiQ',
    appId: '1:203312333339:ios:f86871ecc96b2ebe',
    messagingSenderId: '203312333339',
    projectId: 'konkukbulls-2d7ab',
    databaseURL: 'https://konkukbulls-2d7ab-default-rtdb.firebaseio.com',
    storageBucket: 'konkukbulls-2d7ab.appspot.com',
    iosClientId: '2033123339-qud3ijfuh99thk6v9uj6h0qpqlevui.apps.googleusercontent.com',
    iosBundleId: 'com.my.bccs',
  );
}
